(gh actions) Update version input description and add validation for version format

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       new_version:
-        description: 'New version number (e.g., 1.2.3)'
+        description: 'New version number (e.g., major.minor.patch-[alpha|beta|rc].N.postN)'
         required: true
 
 jobs:
@@ -31,7 +31,10 @@ jobs:
         run: pip install bump2version
 
       - name: Bump version
-        run: |
+          if [[ ! "${{ github.event.inputs.new_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[alpha|beta|rc]\.[0-9]+)?(\.post[0-9]+)?$ ]]; then
+          echo "Error: New version does not match the required format (e.g., major.minor.patch-[alpha|beta|rc].N.postN)." >&2
+          exit 1
+          fi
           bumpversion --new-version ${{ github.event.inputs.new_version }} --no-commit --no-tag minor
 
       - name: Commit and tag version
